version: '3.1'

services:
  postgres:
    image: postgres:16.0-alpine
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - backend-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

volumes:
  backend-db:
